In [9]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}

df = pd.DataFrame(data)

# 데이터 측정
df.describe()

# 모든 데이터 타입 측정
df.describe(include='all')

# 수치형 데이터 측정
df.describe(include=[np.number])

# 특정 열 분석
df['score'].describe()

count     4.000000
mean     87.500000
std       6.454972
min      80.000000
25%      83.750000
50%      87.500000
75%      91.250000
max      95.000000
Name: score, dtype: float64

In [23]:
import pandas as pd

data = {
    'name': ['김철수', '이영희', '박민수', '최지훈', '정소희'],
    'grade': [1, 2, 3, 4, 2],
    'gpa': [4.2, 3.8, 4.5, 3.9, 3.5],
    'department': ['컴퓨터공학', '경영학', '전자공학', '의학', '심리학'],
    'circle': ['프로그래밍', '독서토론', '로봇공학', '봉사활동', '음악감상']
}

df = pd.DataFrame(data)

# 특정 열 선택
selected_df = df[['name', 'department', 'gpa']]
selected_df

# DataFrame column 순서 변경
reordered_cols = df[['department', 'name', 'grade', 'gpa', 'circle']]
reordered_cols

# DataFrame column 이름 변경
df_renamed = df.rename(columns={'name': 'student_name', 'department': 'major'})
df_renamed

  student_name  grade  gpa  major circle
0          김철수      1  4.2  컴퓨터공학  프로그래밍
1          이영희      2  3.8    경영학   독서토론
2          박민수      3  4.5   전자공학   로봇공학
3          최지훈      4  3.9     의학   봉사활동
4          정소희      2  3.5    심리학   음악감상

In [45]:
import pandas as pd

data = {
    'name': ['김철수', '이영희', '박민수', '최지훈', '정소희'],
    'grade': [1, 2, 3, 4, 2],
    'gpa': [4.2, 3.8, 4.5, 3.9, 3.5],
    'department': ['컴퓨터공학', '경영학', '전자공학', '의학', '심리학'],
    'circle': ['프로그래밍', '독서토론', '로봇공학', '봉사활동', '음악감상']
}

# DataFrame 인덱스 지정
df = pd.DataFrame(data)
df = df.set_index('name')
df

# DataFramee row 선택
# Index로 지정된 column의 값만 선택 가능
df.loc['김철수']
df.loc[['김철수', '이영희']]
df.loc['김철수':'최지훈']

# DataFrame 위치 기반 row 선택
df.iloc[1]
df.iloc[[2, 3]]
df.iloc[1:3]

# DataFrame 조건 기반 선택
df.loc[[True, False, True, False, False]]
print(df['grade'] >= 4.0)
df.loc[df['grade'] >= 4.0]
df[df['grade'] == 2]
df[df['grade'] > 2]
df[(df['grade'] == 2) & (df['gpa'] >= 3.7)]

name
김철수    False
이영희    False
박민수    False
최지훈     True
정소희    False
Name: grade, dtype: bool

      grade  gpa department circle
name
이영희       2  3.8        경영학   독서토론

In [51]:
import pandas as pd

data = {
    'name': ['김철수', '이영희', '박민수', '최지훈', '정소희'],
    'grade': [1, 2, 3, 4, 2],
    'gpa': [4.2, 3.8, 4.5, 3.9, 3.5],
    'department': ['컴퓨터공학', '경영학', '전자공학', '의학', '심리학'],
    'circle': ['프로그래밍', '독서토론', '로봇공학', '봉사활동', '음악감상']
}

# DataFrame 인덱스 지정
df = pd.DataFrame(data)
df = df.set_index('name')
df

# DataFrame 단일 column 오름차순, 내림차순 정렬
df.sort_values(by='gpa', ascending=False)

# DataFrame 복수 column 오름차순, 내림차순 정렬
df.sort_values(by=['grade', 'gpa'], ascending=[True, False])

# DataFrame 인덱스 기본 오름차순, 내림차순 정렬
df.sort_index(ascending=False)

      grade  gpa department circle
name
최지훈       4  3.9         의학   봉사활동
정소희       2  3.5        심리학   음악감상
이영희       2  3.8        경영학   독서토론
박민수       3  4.5       전자공학   로봇공학
김철수       1  4.2      컴퓨터공학  프로그래밍